services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: licitacoes-backend
    restart: unless-stopped
    environment:
      - MONGO_URL=${MONGO_URL}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CORREIOS_USUARIO=${CORREIOS_USUARIO}
      - CORREIOS_SENHA=${CORREIOS_SENHA}
      - CORREIOS_CONTRATO=${CORREIOS_CONTRATO}
      - CORREIOS_CARTAO_POSTAGEM=${CORREIOS_CARTAO_POSTAGEM}
      - FRONTEND_URL=https://onlicitacoes.com
    networks:
      - app-network
      - coolify
    expose:
      - "8000"
  frontend:

    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: licitacoes-frontend
    restart: unless-stopped
    ports:
      - "3002:80"
    depends_on:
      - backend
    networks:
      - app-network
    labels:
      - "traefik.http.services.licitacoes-frontend.loadbalancer.server.port=80"
networks:
  app-network:
    driver: bridge
  coolify:
    external: true
